name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: npm install
        run: npm install

      - name: create env file
        run: |
          touch .env
          echo REACT_APP_CAT_API_KEY=${{ secrets.REACT_APP_CAT_API_KEY }} >> .env

      - name: lint
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:5000

      - name: heroku deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        if: github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message), ' '), '#skip')
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "janne-cats-100" 
          heroku_email: "janne.kalliokulju@gmail.com"
          healthcheck: "https://janne-cats-100.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true


  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message), ' '), '#skip')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag, do not do it with skip
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch